export const articles_url='http://newsapi.org/v2/everything'
export const country_code='us'
export const category='general'
export const _api_key='22fd860715af4f7ca4c8de363d8dc363'
export const articles_urlHead='https://newsapi.org/v2/top-headlines'
export const articles_sources='https://newsapi.org/v2/sources'
